### ISSUE TITLE
Path substitutions don't work with BannerPlugin?

### ISSUE THREAD

**Issue by bebraw** [pirelenito/git-revision-webpack-plugin#10]
Hi,

I tried configuration like this:

```javascript
plugins: [
  new GitRevisionPlugin(),
  new webpack.BannerPlugin({
    banner: '[git-revision-version]',
   }),
],
```

It didn't end up replacing the banner content, though, so `[git-revision-version]` went through.

The following solution works:

```javascript
new webpack.BannerPlugin({
  banner: new GitRevisionPlugin.version(),
}),
```

This could be a webpack bug, but just thought to let you know. At least you might want to document this gotcha. Thanks for the plugin. 👍

**Comment by pirelenito** [comment]
Thanks for submitting the issue, and I'm glad you found this plugin useful! ❤️

I currently do the path substitution at (as you can check [here](https://github.com/pirelenito/git-revision-webpack-plugin/blob/master/lib/build-file.js#L16)):

```js
compilation.mainTemplate.plugin('asset-path', function (path) {
  return path.replace(replacePattern, data)
})
```

Do you know if I should do it in another hook as well? Otherwise I'll try to dig the way.

Thanks again!

**Comment by bebraw** [comment]
I think I know what's going on. Take a look at [BannerPlugin](https://github.com/webpack/webpack/blob/master/lib/BannerPlugin.js) code. It captures the initial `banner` string passed to it, but does **not** push it through evaluation. I would look into [css-loader](https://github.com/webpack-contrib/css-loader) to see how it handles it. This needs to be fixed on webpack level.

**Comment by pirelenito** [comment]
Hi @bebraw,

Could you confirm that the issue was at webpack level?

**Comment by bebraw** [comment]
Yeah, see https://github.com/webpack/webpack/issues/4252 . `BannerPlugin` should use `compilation.getPath`. It's still waiting for a PR, though.
