### ISSUE TITLE
Add branch name

### ISSUE THREAD

**Issue by pke** [pirelenito/git-revision-webpack-plugin#11]
It would be nice if this plugin could also fetch the branch name and if its dirty.

**Comment by pirelenito** [comment]
Hi there! Thanks for submitting it.

What would be the use-case?

**Comment by pke** [comment]
So that we can display it in the apps about dialog page and instantly know from which branch this was compiled without having to check in the repo.
This could also be used in a CI scenario that a unit test makes sure the release build is built from the master branch only.

**Comment by pirelenito** [comment]
That could definitely be a new feature for us to support.

However, in the current projects I work at, the `VERSION` and `COMMITHASH` information is enough to identify a release.

So, in the spirit of keeping this plugin slim, would it make sense for you to achieve your use case by using the [DefinePlugin](https://webpack.js.org/plugins/define-plugin/#components/sidebar/sidebar.jsx) directly to make the information available at build time?

**Comment by pirelenito** [comment]
Released in https://github.com/pirelenito/git-revision-webpack-plugin/releases/tag/v2.5.0
