### ISSUE TITLE
Allow commithash and version to take an optional callback to be passed to runGitCommand

### ISSUE THREAD

**Issue by dwayne** [pirelenito/git-revision-webpack-plugin#12]
`runGitCommand` can take a callback, see [here](https://github.com/pirelenito/git-revision-webpack-plugin/blob/74faeda7b663f4e265a487a4a70139c4ef14377a/lib/helpers/run-git-command.js#L6). But, we don't allow one to be passed along, see [here](https://github.com/pirelenito/git-revision-webpack-plugin/blob/74faeda7b663f4e265a487a4a70139c4ef14377a/lib/index.js#L41-L53).

**Comment by pirelenito** [comment]
That is fine, then it just runs synchronously. Do you have a requirement to have it running asynchronously?

**Comment by dwayne** [comment]
@pirelenito No requirement. Just something I noticed when I was trying to handle an error. That there is no way to do it asynchronously even though the underlying function takes a callback. So I felt like mentioning it for completeness.

**Comment by pirelenito** [comment]
That is an implementation detail that is not documented, and since these functions were designed to be used while constructing Webpack configurations, they will most likely will be called synchronously.

Thanks for getting in touch,

Cheers
