### ISSUE TITLE
Doc: By default no branch is generated, API sample code wrong

### ISSUE THREAD

**Issue by pke** [pirelenito/git-revision-webpack-plugin#16]
https://github.com/pirelenito/git-revision-webpack-plugin#plugin-api

The first usage example shows `BRANCH` being used in the define plugin, but the call to `new GitRevisionPlugin()` doesn't include the `branch: true` option so no branch name is generated.

**Comment by pirelenito** [comment]
Sorry about the confusion in the documentation and API, but the `.branch()` api actually works without the flag being enabled.

You can check the implementation https://github.com/pirelenito/git-revision-webpack-plugin/blob/master/lib/index.js#L71

**Comment by pke** [comment]
By default it's false, I could see that. The example code in the readme is still wrong, isn't it?

**Comment by pirelenito** [comment]
The option affects path substitution and creating the BRANCH file.

**Comment by pke** [comment]
Right, thanks! Great plugin. Will help to improve our customer services in connection with sentry.io a great step.
