### ISSUE TITLE
Support for webpack 4

### ISSUE THREAD

**Issue by b1f6c1c4** [pirelenito/git-revision-webpack-plugin#21]
This plugin cause `DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead`

> DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
>     at buildFile (C:\Users\b1f6c1c4\Documents\Github\ballot\frontend\node_modules\git-revision-webpack-plugin\lib\build-file.js:6:12)
>     at GitRevisionPlugin.apply (C:\Users\b1f6c1c4\Documents\Github\ballot\frontend\node_modules\git-revision-webpack-plugin\lib\index.js:30:3)
>     at webpack (C:\Users\b1f6c1c4\Documents\Github\ballot\frontend\node_modules\webpack\lib\webpack.js:37:12)
>     at processOptions (C:\Users\b1f6c1c4\Documents\Github\ballot\frontend\node_modules\webpack-cli\bin\webpack.js:427:16)
>     at yargs.parse (C:\Users\b1f6c1c4\Documents\Github\ballot\frontend\node_modules\webpack-cli\bin\webpack.js:502:3)
>     at Object.parse (C:\Users\b1f6c1c4\Documents\Github\ballot\frontend\node_modules\webpack-cli\node_modules\yargs\yargs.js:539:18)
>     at C:\Users\b1f6c1c4\Documents\Github\ballot\frontend\node_modules\webpack-cli\bin\webpack.js:212:8
>     at Object.<anonymous> (C:\Users\b1f6c1c4\Documents\Github\ballot\frontend\node_modules\webpack-cli\bin\webpack.js:504:3)
>     at Module._compile (module.js:660:30)
>     at Object.Module._extensions..js (module.js:671:10)
>     at Module.load (module.js:573:32)
>     at tryModuleLoad (module.js:513:12)
>     at Function.Module._load (module.js:505:3)
>     at Function.Module.runMain (module.js:701:10)
>     at startup (bootstrap_node.js:194:16)
>     at bootstrap_node.js:618:3

**Comment by dderjoel** [comment]
push!

**Comment by pirelenito** [comment]
Sorry for the delay, but the PR is finally here #27 🎉

**Comment by pirelenito** [comment]
The merged PR was actually
