### ISSUE TITLE
It does not do anything with Angular

### ISSUE THREAD

**Issue by festim-deari** [pirelenito/git-revision-webpack-plugin#24]
EDITED
I found a solution: Declare VERSION, COMMITHASH and BRANCH as follows:
`declare var VERSION:string, COMMITHASH:string, BRANCH:string`
And then in the Component i saved the values in variables:
`version:string = VERSION`
The problem that I had was because of TypeScript. In TypeScript I had to declare them first.
-------------------

I am using webpack 3 and angular 5 in my project.
I defined a new plugin in webpack as shown in the readme, and added {{ VERSION }} in my angular component template, but unfortunately it did not show anything. It does not throw any error though.

I added this in the webpack config file:
```
const GitRevisionPlugin = require('git-revision-webpack-plugin');
const gitRevisionPlugin = new GitRevisionPlugin();

plugins: [
    new DefinePlugin({
      'VERSION': JSON.stringify(gitRevisionPlugin.version()),
      'COMMITHASH': JSON.stringify(gitRevisionPlugin.commithash()),
      'BRANCH': JSON.stringify(gitRevisionPlugin.branch()),
    }),
  ]
```
Have I done something wrong, or does it not work the way I have used it at all?
Thank you in advance!

**Comment by pirelenito** [comment]
Glad that you found a solution ❤️! Closing this issue for now.
