### ISSUE TITLE
Add support for annotated tags?

### ISSUE THREAD

**Issue by RadBoris** [pirelenito/git-revision-webpack-plugin#25]
Annotated tags are more useful for automated deployment and this will be a nice addition to the library.

**Comment by pirelenito** [comment]
Thanks for the suggestion! You can already customize how the plugin finds the tag using https://github.com/pirelenito/git-revision-webpack-plugin#versioncommand-describe---always

Does that works?

**Comment by pirelenito** [comment]
I'll close the issue, but feel free to open it again if my reply didn't answer your question.
