### ISSUE TITLE
Get date of last commit

### ISSUE THREAD

**Issue by lvl99** [pirelenito/git-revision-webpack-plugin#26]
Is it possible to get the date of the last commit?

**Comment by pirelenito** [comment]
What do you mean?

The plugin currently outputs just the `VERSION` and `COMMITHASH` information, do you want an extra `DATE` or something?

Cheers!

**Comment by pirelenito** [comment]
I'm closing the issue due to inactivity, but feel free to repoen again.

Cheers!

**Comment by tartinesKiller** [comment]
If anyone is still interested in last commit date time, I've forked and implemented it, a pull request is actually awaiting. Link to the repo: [https://github.com/tartinesKiller/git-revision-webpack-plugin](url)

**Comment by lvl99** [comment]
Sorry @pirelenito, must have missed the notifications before.

Thanks @tartinesKiller !

**Comment by k-funk** [comment]
Would also like to see this feature. A simple `git log -1 --format=%cI` would be helpful for me. Personally the format doesn't matter for my current usage, but it might to some (see https://git-scm.com/docs/pretty-formats for formatting options).
