### ISSUE TITLE
Improvement/rollback: lower (or don't specify) engine.node version requirement

### ISSUE THREAD

**Issue by renotoaster** [pirelenito/git-revision-webpack-plugin#31]
3.x.x introduces `engines.node` as `>=8.0.0` in `package.json`.

Installing `git-revision-webpack-plugin` with `yarn` throws an error when running node 6.x because of the above. This breaks a lot of production builds on servers running older Node LTS (6.x).

I ran the test and they pass with node 6.14.2, and I tested with webpack4 boilerplate (https://github.com/cvgellhorn/webpack-boilerplate) to see if I can actually get the hash in-code and it works.

Not to say these tests are empirical, but it seems like requiring `node>=8` isn't needed.

Suggested fix:
a) lower `engines.node` to 6.x (or even lower if if works)
b) remove the requirement completely, as it seems to do more harm than good

**Comment by pirelenito** [comment]
Super weird!

I just pushed a new patch `3.0.2` and the problem seems to be fixed now.

Can you try again?

**Comment by renotoaster** [comment]
3.0.2 does indeed fix this issue, thanks!
