### ISSUE TITLE
Is there a way to get the short-hash?

### ISSUE THREAD

**Issue by iDVB** [pirelenito/git-revision-webpack-plugin#37]
Is there a way to get the short-hash?

**Comment by tlattimore** [comment]
According to [the README](https://github.com/pirelenito/git-revision-webpack-plugin#commithashcommand-rev-parse-head) the `commithashCommand` should be overridable. But in my testing I am not able to get it to work with something like `rev-parse --short HEAD`—which returns a short hash.

**Comment by ream88** [comment]
I have this in my webpack config and it works perfectly fine: 

```js
new GitRevisionPlugin({
  commithashCommand: 'rev-parse --short HEAD'
})
```
