### ISSUE TITLE
Add date to version

### ISSUE THREAD

**Issue by abentele** [pirelenito/git-revision-webpack-plugin#40]
Currently my version looks like
1.1-59-gdcd4eea

I would like to append the last commit date to the version string:
1.1-0-gdcd4eea-2018-12-30

This version should be saved to the VERSION file.

Issue #26 is related, but not the same.

**Comment by tartinesKiller** [comment]
Maybe you can get the desired format js-side, by appending VERSION and a formatted LASTCOMMITDATETIME with Date or moment.js?
