### ISSUE TITLE
Pre-hook fetch to ensure local git is up to date with remote

### ISSUE THREAD

**Issue by jufemaiz** [pirelenito/git-revision-webpack-plugin#58]
The ability to undertake a fetch as a pre-hook to ensure that the local git is up to date with remote would be useful.

At the moment I need to run this in CI to ensure that, particularly the tags, are up to date.

```bash
git fetch --all --tags

npm run build
```

A pre-hook that could run the fetch would be great.

**Comment by pirelenito** [comment]
Thanks for the suggestion, but I'm currently not accepting any new features to the package.
