### ISSUE TITLE
How does plugin works without git installed in Docker container?

### ISSUE THREAD

**Issue by uidoyen** [pirelenito/git-revision-webpack-plugin#60]
I am trying to understand that how does this plugin fetch git `COMMIT_HASH` and able to execute git commands without git installed in Docker container.

**Comment by begoat** [comment]
I guess it won't be able to do that.

I encountered an error on samiliar situation. Logs are shown below.
```shell
/bin/sh: git: not found
Error resolving webpackConfig Error: Command failed: git describe --always --tags
/bin/sh: git: not found
```

**Comment by pirelenito** [comment]
Hello 👋 

The plugin needs `git` to be available. So a solution could be to have `git` installed in the container or If you know you will be running in an environment without git, disable the plugin in Webpack.

**Comment by pirelenito** [comment]
I'll close the issue, but feel free to re-open if the answer wasn't satisfactory. 👍
