### ISSUE TITLE
🚨 Potential Command Injection - Generic (CWE-77)

### ISSUE THREAD

**Issue by huntr-helper** [pirelenito/git-revision-webpack-plugin#61]
👋 Hello, @pirelenito - a potential high severity Command Injection - Generic (CWE-77) vulnerability in your repository has been disclosed to us.

#### Next Steps

1️⃣  Visit **https://huntr.dev/bounties/2-other-pirelenito/git-revision-webpack-plugin** for more advisory information.

2️⃣  **[Sign-up](https://huntr.dev/)** to validate or speak to the researcher for more assistance.

3️⃣ Propose a patch or outsource it to our community - whoever fixes it gets paid.

✏️ **NOTE**: If we don't hear from you in *14 days*, we will proactively source a fix for this vulnerability (and open a PR) to ensure community safety.

---

#### Confused or need more help?

- Join us on our **[Discord](https://huntr.dev/discord)** and a member of our team will be happy to help! 🤗

- Speak to a member of our team: @JamieSlome

---

*This issue was automatically generated by [huntr.dev](https://huntr.dev) - a bug bounty board for securing open source code.*

**Comment by pirelenito** [comment]
This is implemented as designed. And it was previously reported #49

**Comment by adam-nygate** [comment]
> This is implemented as designed. And it was previously reported #49

Sorry about that pirelenito! We've added a task to our backlog to help prevent repeat disclosures.

CC: @JamieSlome

**Comment by JamieSlome** [comment]
Marked as invalid in our database - thanks for the heads up @pirelenito! 🍰
